swagger: "2.0"
info:
  description: "API to manage subscriptions at our own subscriptions provider, and Chargebee provider"
  version: "0.0.1"
  title: "Subscriptions Manager"
tags:
  - name: "admin"
    description: "Admin API operations"
  - name: "plans"
    description: "API operations to control plans"
  - name: "coupons"
    description: "API operations to control coupons"
  - name: "events"
    description: "API operations for incoming Domain Event messages"
  - name: "subscriptions"
    description: "API bulk subscriptions operations"
  - name: "subscription"
    description: "API operations to control a specific subscription"
  - name: "at home offer"
    description: "API operations to control at home offers"
  - name: "invoices"
    description: "API operations to control invoices"
  - name: "addons"
    description: "API operations to control addons"

consumes:
  - application/json
produces:
  - application/json

parameters:
  familyIdPathParam:
    name: familyId
    in: path
    description: "Rooster family account identifier"
    required: true
    type: integer
    format: int32

definitions:
PlanResponse:
    type: object
    properties:
      key:
        type: string

paths:

  /plans:
    get:
      tags:
        - "plans"
      summary: "Lists all available subscription plans"
      description: "Lists all available subscription plans"
      parameters:
        - $ref: '#/parameters/familyIdPathParam'
      responses:
        200:
          description: "Returns list of plans."
          schema:
            type: array
            items:
              $ref: "#/definitions/PlanResponse"
